# -*- coding: utf-8 -*-
"""Introduction to Numpy, Pandas and matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19w-Ht0qrKrDidfk1MhVxXv_jYupDu0qO

## Lab 4: Introduction to Data Mining with NumPy, Pandas, and Matplotlib

1.   সূচির আইটেম
2.   সূচির আইটেম



1. Introduction to NumPy
   1. Creating Arrays
   2. Array Operations
   3. Indexing and Slicing
   4. Exercises

2. Introduction to Pandas
   1. Creating DataFrames
   2. DataFrame Operations
   3. Data Cleaning
   4. Selecting Data from DataFrame
     -  Selecting by Position (`.iloc`)
     -  Selecting by Label (`.loc`)
   5. Boolean Indexing
   6. Setting Values in DataFrame
   7. Exercises

3. Data Visualization with Matplotlib
   1. Line Plots
   2. Scatter Plots
   3. Bar Plots
   4. Exercises

[লিঙ্ক টেক্সট](https://)## 1. Introduction to NumPy

### 1.1 Creating Arrays
NumPy is a powerful library for numerical computing in Python. It provides support for multidimensional arrays and various mathematical operations. Let's start by creating arrays.
"""

import numpy as np

# Creating a 1-dimensional array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)

# Creating a 2-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr2d)

a= np.array([1,2,3])
b = np.array([(1,2,3),(4,5,6)], dtype = float)

"""Initial placeholders"""

#Create an array of zeros
np.zeros((3,4))

#Create an array of ones
np.ones((2,3,4),dtype=np.int16)

#Create an array of evenly spaced values (step value)
np.arange(10,25,5)

#Create an array of evenly spaced values (number of samples)
np.linspace(0,2,9)

#Create a constant array
np.full((2,2),7)

#Create a 2X2 identity matrix
np.eye(2)

#Create an array with random values
np.random.random((2,2))

#Create an empty array
np.empty((2,5))

"""### 1.2 Array Operations
NumPy allows performing various operations on arrays, such as element-wise operations, aggregation, and broadcasting.

# Basic array operations
"""

arr_sum = np.sum(arr1d)
arr_mean = np.mean(arr1d)
arr_max = np.max(arr1d)

print("\nArray Operations:")
print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Max:", arr_max)

#Subtraction
c =  np.ones([1,3])
g = c-b
print(g)

ab = a-b
print(ab)
np.subtract(a,b)

#Addition
np.add(b,a)

#Division
np.divide(a,b)

#multiplication
print(np.multiply(a,b))

#exponentiation
print(np.exp(b))

##square root
print(np.sqrt(b))

#print sines of an array
print(np.sin(a))

#sorint array
np.sort(a)

"""### 1.3 Indexing and Slicing
You can access individual elements or slices of elements in a NumPy array using indexing and slicing.

"""

# Indexing and slicing
print("\nIndexing and Slicing:")
print("Element at index 2:", arr1d[2])
print("Slice from index 1 to 3:", arr1d[1:4])

"""### 1.4 Exercises
1. Create a 3x3 NumPy array with random integers between 1 and 10. Compute the sum of all elements in the array.
2. Given the array `arr1 = np.array([12, 52, 33])` and `arr2 = np.array([43, 52, 66])`, perform element-wise multiplication of the two arrays.

## 2. Introduction to Pandas

### 2.1 Creating DataFrames
Pandas provides a DataFrame data structure that allows us to work with labeled data efficiently. Let's start by creating a DataFrame.
"""

import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age': [25, 30, 22, 28, 24],
        'Salary': [50000, 60000, 45000, 70000, 55000]}

df = pd.DataFrame(data)
print("DataFrame:")
print(df)

"""### 2.2 Selecting Data from DataFrame
Pandas provides various methods to select data from a DataFrame.

#### 2.2.1 Selecting by Position (`.iloc`)
You can use `.iloc` to select rows and columns by their integer positions.

"""

# Selecting the first row
row_0 = df.iloc[0]
print("\nSelecting by Position (iloc):")
print("First Row:")
print(row_0)

# Selecting the value in the second row and 'Age' column
value_2nd_row_age_col = df.iloc[1, df.columns.get_loc('Age')]
print("Value in the 2nd Row and 'Age' Column:", value_2nd_row_age_col)

"""#### 2.2.2 Selecting by Label (`.loc`)
You can use `.loc` to select rows and columns by their labels.

"""

# Selecting rows with specific labels
selected_rows = df.loc[[1, 3]]
print("\nSelecting by Label (loc):")
print("Selected Rows:")
print(selected_rows)

# Selecting a specific cell by label
cell_label = df.loc[2, 'Salary']
print("Value at Row 2 and 'Salary' Column:", cell_label)

"""### 2.3 Boolean Indexing
Boolean indexing allows selecting rows based on conditions.
"""

# Boolean indexing
high_salary_employees = df[df['Salary'] > 55000]
print("\nBoolean Indexing:")
print("Employees with Salary > 55000:")
print(high_salary_employees)

"""### 2.4 Setting Values in DataFrame
You can use the `.loc` method to set values in a DataFrame.
"""

# Setting a new value in the DataFrame
df.loc[0, 'Age'] = 26
print("\nSetting Values in DataFrame:")
print("DataFrame with Updated Age:")
print(df)

# Setting a new column with default values
df['Experience'] = [2, 5, 1, 7, 3]
print("\nAdding a New Column:")
print(df)

"""### 2.5 Exercises
1. Select the last two rows of the DataFrame `df`.
2. Create a new DataFrame containing only the rows where the 'Age' is less than 30 and the 'Salary' is greater than 50000.
3. Set the salary of 'Charlie' to 48000 in the DataFrame `df`.

## 3. Data Visualization with Matplotlib

### 3.1 Line Plots
Matplotlib is a powerful library for data visualization in Python. Let's create a simple line plot.
"""

import matplotlib.pyplot as plt

# Generating data for the plot
x = np.linspace(0, 10, 100)
y = np.sin(x)

# Creating a line plot
plt.plot(x, y)
plt.xlabel('x-axis')
plt.ylabel('y = sin(x)')
plt.title('Simple Line Plot')
plt.show()

"""### 3.2 Scatter Plots
Scatter plots are useful for visualizing the relationship between two variables.

"""

# Generating data for the scatter plot
x = np.random.rand(50)
y = np.random.rand(50)

# Creating a scatter plot
plt.scatter(x, y)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('Scatter Plot')
plt.show()

"""### 3.3 Bar Plots
Bar plots are used to compare different categories.

"""

# Generating data for the bar plot
categories = ['A', 'B', 'C', 'D']
values = [15, 20, 12, 18]

# Creating a bar plot
plt.bar(categories, values)
plt.xlabel('Categories')
plt.ylabel('Values')
plt.title('Bar Plot')
plt.show()

"""### 3.4 Exercises
1. Generate a random dataset with two features (X and Y) and create a scatter plot to visualize the relationship between them.
2. Create a bar plot to compare the average salary of different age groups from the DataFrame `df`.
"""

